version: '3.7'
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: redis-server --requirepass admin
  postgresql:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=node-redis
      - POSTGRES_DB=node-redis
